name: /notes

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 0-6

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: build
        uses: actions/setup-node@v1.1.2
        with:
          node-version: "10.16"
      - run: |
          npm install
          npm run build

      - name: deploy
        uses: peaceiris/actions-gh-pages@v2.2.0
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./public
